package ${groupId}.${artifactId}.modelo;
// Generated 21-01-2018 05:32:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer idrol;
     private String nombre;
     private Set rolmenus = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Rol() {
    }

    public Rol(String nombre, Set rolmenus, Set usuarios) {
       this.nombre = nombre;
       this.rolmenus = rolmenus;
       this.usuarios = usuarios;
    }
   
    public Integer getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(Integer idrol) {
        this.idrol = idrol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getRolmenus() {
        return this.rolmenus;
    }
    
    public void setRolmenus(Set rolmenus) {
        this.rolmenus = rolmenus;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


