package ${groupId}.modelo;
// Generated 21-01-2018 05:32:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private Rol rol;
     private String nombre;
     private String clave;
     private Set usuarios = new HashSet(0);

    public Usuario() {
    }

    public Usuario(Rol rol, String nombre, String clave, Set equipos, Set programarecepcionitems, Set seriedescansos, Set ors, Set mantencions, Set descansos, Set programarecepcions, Set oms, Set conductors, Set ots, Set ods, Set combustibles, Set usuarios) {
       this.rol = rol;
       this.nombre = nombre;
       this.clave = clave;
       this.usuarios = usuarios;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    public Set getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

}


